routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FaqController;


use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\DonetController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\PublicController;
use PHPUnit\TextUI\XmlConfiguration\Group;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CarouselController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\Getdonatecontoller;
use App\Http\Controllers\SellbookController;

use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\DonatebookController;

use App\Http\Controllers\PublicPageController;

use App\Http\Controllers\RequestbookController;

use App\Http\Controllers\DonetCommentController;
use App\Http\Controllers\PublicProductController;
use App\Http\Controllers\PublicProductDetailsController;
 
use App\Http\Controllers\ProductController; 
 
use App\Http\Controllers\EarnpointController;
use App\Http\Controllers\UserorderController;
 
 
 
 
 
 

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });





//this is user authentication
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';


//This is frontend route
Route::controller(PublicController::class)->group(function(){
    Route::get('/','home')->name('homepage');
    Route::post('/logout',[PublicController::class,'logout'])->name('logout')->middleware('auth');
});

Route::middleware('auth')->controller(PublicProductController::class)->group(function(){

    Route::get('/bestbook','bestbook')->name('bestbook');
    Route::get('/newcollection','newcollection')->name('newcollection');
    Route::get('/oldbook','oldbook')->name('oldbook');
    Route::get('/getdonate','getdonate')->name('getdonate');
    Route::get('/earnpoint','earnpoint')->name('earnpoint');
    Route::post('/earnpoints','store')->name('earnpoints.store');
    Route::patch('/earnpoints/{earnpoint}','update')->name('earnpoints.update');
    Route::delete('/earnpoint/{earnpoint}','destroy')->name('earnpoints.destroy');

});


 
 
 
Route::middleware('auth')->controller(PublicPageController::class)->group(function(){
   
 
 
 
    Route::get('/aboutus','aboutus')->name('aboutus');
    Route::get('/contactus','contactus')->name('contactus');
    Route::get('/faq','faq')->name('faq');
    Route::get('/upcomingEvent','upcomingEvent')->name('upcomingEvent');
    Route::get('/eventDetails/{id}','eventDetails')->name('eventDetails');

 
  
   
 
 

 

});
 

Route::middleware('auth')->controller(PublicProductDetailsController::class)->group(function(){

    Route::get('/bookdetails/{bookdetail}','bookdetails')->name('bookdetails');
 
    Route::get('/donetbookdetails/{donetbookdetail}','donetbookdetails')->name('donetbookdetails');
    // Route::get('/carts/{cart}','cartproduct')->name('carts');
 

 
 
    // Route::get('/donetbookdetails/{donetbookdetail}', 'donetbookdetails')->name('donetbookdetails');
 
    // Route::post('/donetbookdetails/{donetbookdetail}','donetbookdetails')->name('donetbookdetails');
 
    // Route::get('/donetbookdetails/{donetbookdetail}','donetbookdetails')->name('donetbookdetails');
 


 

    Route::get('/cart/{cart}','cart')->name('cart');
 
    Route::get('/payment/{pay}','payment')->name('payment');
    // Route::post('products/{product}/cart','store')
    //  ->name('carts.store');
 


});

Route::middleware('auth')->group(function(){
    Route::get('sellbooks/create',[SellbookController::class,'create'])->name('sellbooks.create');
    Route::post('sellbooks/store',[SellbookController::class,'store'])->name('sellbooks.store');

    Route::get('requestbooks/create',[RequestbookController::class,'create'])->name('requestbooks.create');
    Route::post('requestbooks/store',[RequestbookController::class,'store'])->name('requestbooks.store');

    Route::get('donatebooks/create',[DonatebookController::class,'create'])->name('donatebooks.create');
    Route::post('donatebooks/store',[DonatebookController::class,'store'])->name('donatebooks.store');
    Route::resource('donatebooks.comments',DonetCommentController::class)->shallow();
    Route::resource('sellbooks.comments', CommentController::class)->shallow();

});


Route::middleware('auth','isAdmin')->group(function(){

    //Tag route
    Route::get('/tags/trash', [TagController::class,'trash'])->name('tags.trash');
    Route::patch('/tags/trash/{id}', [TagController::class,'restore'])->name('tags.restore');
    Route::delete('/tags/trash/{id}', [TagController::class,'delete'])->name('tags.delete');
    Route::resource('tags', TagController::class);
    Route::resource('users', UserController::class);
    Route::resource('carousels', CarouselController::class);
 
 
 
    
    Route::resource('products', ProductController::class);

    Route::resource('earnorders', EarnpointController::class);
    
 

 
 
    
 
 
 
    Route::resource('getdonates', Getdonatecontoller::class);
    //category route
    Route::get('/categories/trash', [CategoryController::class,'trash'])->name('categories.trash');
    Route::patch('/categories/trash/{id}', [CategoryController::class,'restore'])->name('categories.restore');
    Route::delete('/categories/trash/{id}', [CategoryController::class,'delete'])->name('categories.delete');
    Route::resource('categories', CategoryController::class);
    //requestbook route
    Route::get('/reqapproved/{id}',[RequestbookController::class,'approved'])->name('reqapproved');
    Route::get('/reqcancle/{id}',[RequestbookController::class,'cancle'])->name('reqcancle');
    Route::get('/requestbooks/trash', [RequestbookController::class,'trash'])->name('requestbooks.trash');
    Route::patch('/requestbooks/trash/{id}', [RequestbookController::class,'restore'])->name('requestbooks.restore');
    Route::delete('/requestbooks/trash/{id}', [RequestbookController::class,'delete'])->name('requestbooks.delete');
    Route::resource('requestbooks', RequestbookController::class)->except('create','store');
    //sellbook route
    Route::get('/sellapproved/{id}',[SellbookController::class,'approved'])->name('sellapproved');
    Route::get('/sellcancle/{id}',[SellbookController::class,'cancle'])->name('sellcancle');
    Route::get('/sellbooks/trash', [SellbookController::class,'trash'])->name('sellbooks.trash');
    Route::patch('/sellbooks/trash/{id}', [SellbookController::class,'restore'])->name('sellbooks.restore');
    Route::delete('/sellbooks/trash/{id}', [SellbookController::class,'delete'])->name('sellbooks.delete');
    Route::resource('sellbooks', SellbookController::class)->except('create','store');

    //Donate-book route
    Route::get('donets/{donet}',[DonetController::class,'Drequest'])->name('donets.create');
    Route::get('/approved/{id}',[DonetController::class,'approved'])->name('approved');
    Route::get('/cancle/{id}',[DonetController::class,'cancle'])->name('cancle');
    Route::get('/donatebooks/trash', [DonatebookController::class,'trash'])->name('donatebooks.trash');
    Route::patch('/donatebooks/trash/{id}', [DonatebookController::class,'restore'])->name('donatebooks.restore');
    Route::delete('/donatebooks/trash/{id}', [DonatebookController::class,'delete'])->name('donatebooks.delete');
    Route::resource('donatebooks', DonatebookController::class)->except('create','store');
    //Event route
    Route::get('/events/trash', [EventController::class,'trash'])->name('events.trash');
    Route::patch('/events/trash/{id}', [EventController::class,'restore'])->name('events.restore');
    Route::delete('/events/trash/{id}', [EventController::class,'delete'])->name('events.delete');

    Route::resource('events', EventController::class);







    Route::get('/user',[UserController::class,'user'])->name('user.register');
    Route::resource('faqs',FaqController::class);
    Route::resource('banners', BannerController::class);
    Route::get('/user',[UserController::class,'user'])->name('user.register');

    Route::resource('faqs',FaqController::class);

});

 
    Route::resource('profiles',ProfileController::class)->middleware('auth');
    
 
    Route::resource('profile',ProfileController::class)->middleware('auth');

 
    Route::post('/faq',[FaqController::class,'store'])->name('faq.store');

    Route::resource('faqs',FaqController::class);



    Route::get('/user',[UserController::class,'user'])->name('user.register');

    Route::middleware('auth','isAdmin')->controller(AdminController::class)->prefix('admin')->group(function(){
        Route::get('/dashboard','dashboard')->name('admin.dashboard');
        Route::get('/productlist','productlist')->name('admin.productlist');
    });



 
 Route::post('products/{product}/cart', [CartController::class, 'store'])
 ->name('carts.store')
 ->middleware('auth');

 

 Route::resource('contacts', ContactUsController::class);
 Route::resource('abouts', AboutController::class);
 Route::get('/aboutus',[AboutController::class,'aboutus'])->name('aboutus');
 Route::get('/useroders/{userorder}',[UserorderController::class,'show'])->name('userorders.show');
 




 

resources/views/frontend/more_page/aboutus.blade.php
<x-frontend.layout.master>
  @slot('title')
  AboutUs
  @endslot

  <div class="container d-flex justify-content-center">
    @if(isset($banner->image))
    <div class="card ">
        <img src="{{ asset('/storage/banner/' . $banner->image) }}" alt="Banner"style="width:100%">
    </div>
    @endif
</div>
  <section class="" style="background-color: #f4f9fc;">
    <div class="container mt-5">
      <div class="row">
        <div class="col-6">
          <img src="images/about/we.png" alt="" class="img-fluid" style="height:300px ;">
          <h3 class="mt-5 text-primary">Who we are</h3>
          <p style="text-align:justify;"class="text-dark">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.</p>
        </div>
        <div class="col-6">
          <img src="images/about/about_right.jpg" alt="" class="img-fluid" style="height: 300px;">
          <h3 class="mt-5 text-primary  ">Our Mission and Vission</h3>
          <p style="text-align:justify;"class="text-dark">Sed ut perspiciatis unde omnis iste natus error sit voluptat accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur adipisci velit.</p>
        </div>
      </div>
    </div>

    <section class="cta-section ">
      <div class="container">
        <div class="cta position-relative">
          <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="counter-stat">
                <i class="icofont-doctor"></i>
                <span class="h3">58</span>k
                <p>Satisfy People</p>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="counter-stat">
                <i class="icofont-flag"></i>
                <span class="h3">700</span>+
                <p>Daily Sell Book</p>
              </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="counter-stat">
                <i class="icofont-badge"></i>
                <span class="h3">40</span>+
                <p>Daily Request Book</p>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="counter-stat">
                <i class="icofont-globe"></i>
                <span class="h3">20</span>
                <p>Daily Donate Book</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>



    <div class="container text-center mb-5" style="margin-top: 120px;">
      <div class="row">
        <h2 class="mt-5">About Us</h2>
        @foreach ($abouts as $about)




        <div class="col-3 card ml-1 mt-5">

          @if(isset($about->image))
          <img src="{{asset('/storage/aboutus/'.$about->image)}}" alt="" style="width:500px;height:250px" class="img-fluid">
          @endif
          <h4>{{$about->title}}</h4>
          <p>{{$about->description}}</p>
        </div>



        @endforeach
      </div>
    </div>


</x-frontend.layout.master>

resources/views/frontend/more_page/contactus.blade.php
 <x-frontend.layout.master>
    @slot('title')
    ContactUS
    @endslot
<!-- Slider Start -->
<div class="container d-flex justify-content-center">
    @if(isset($banner->image))
    <div class="card ">
        <img src="{{ asset('/storage/banner/' . $banner->image) }}" alt="Banner"style="width:100%">
    </div>
    @endif
</div>
<section class=""  >
<!-- /Slider end -->

  <div class="container ">
      
    
   <x-frontend.form.card_header text="Contact Us" class="text-white rounded"/>
   <div class="card-body">
    <form class="row g-3" role="form" action="{{  route('contacts.store') }}" method="post" enctype="multipart/form-data">

        @csrf
        @method('post')
            
            <br>
            <x-backend.alertmessage.alertmessage type="success"/>
            <div class="col-md-6">
                <x-frontend.form.input name="fullname" text="Your Name" type="text" :value="old('fullname')"/>
            </div>
            <div class="col-md-6">
                <x-frontend.form.input name="mobile" text="Phone No" type="tel" pattern="[0-9]{11}" :value="old('mobile')"/>
            </div>
            <div class="col-md-6">
                <x-frontend.form.input name="email" text="Your E-mail" type="text" :value="old('email')"/>
            </div>
            
            
           
            <div class="col-md-6">
                <x-frontend.form.input name="message" text="Leave your message " type="textarea"  :value="old('message')"/>
            </div>
           
            <button type="submit" class="btn btn-primary w-50 mx-auto" name="submit">Submit</button>
             

            </div>
        </form>   
   </div>
    
</div>

</x-frontend.layout.master>

     

resources/views/frontend/more_page/eventDetails.blade.php
 <x-frontend.layout.master>
    @slot('title')
    Events
    @endslot
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />

<div class="container">
    <!-- start event block -->
    <div class="row align-items-center event-block no-gutters margin-40px-bottom">
        <div class="col-lg-5 col-sm-12">
            <div class="position-relative">
                <img src="{{asset('/storage/events/'.$event->image)}}" alt="" style="width:450px;height:250px">

            </div>
        </div>
        <div class="col-lg-7 col-sm-12">
            <div class="padding-60px-lr md-padding-50px-lr sm-padding-30px-all xs-padding-25px-all">
                <h5 class="margin-15px-bottom md-margin-10px-bottom font-size22 md-font-size20 xs-font-size18 font-weight-500"><a href="event-details.html" class="text-theme-color">{{$event->title}}</a></h5>
                <ul class="event-time margin-10px-bottom md-margin-5px-bottom">
                    <li><i class="fas fa-calendar-days margin-5px-right"></i> Date : {{$event->date}}</li>
                      <li><i class="far fa-clock margin-10px-right"></i> {{$event->time}}</li>
                    <li><i class="fas fa-user margin-5px-right"></i> Speaker : {{$event->cheif_guest}}</li>
                    <li><i class="fas fa-location-dot margin-5px-right"></i> Location : {{$event->venue}}</li>


                </ul>

            <p>
             {{ $event->details}}


               <a href="{{route('upcomingEvent')}}" class=" btn btn-outline-dark btn-sm">Read Less</a>


            </p>

                <!--<p>$event->details</p>
                <a class="butn small margin-10px-top md-no-margin-top" href="event-details.html">Read More <i class="fas fa-long-arrow-alt-right margin-10px-left"></i></a>-->
            </div>
        </div>
    </div>
    <hr>
    <!-- end event block -->



</div>

</x-frontend.layout.master>

resources/views/frontend/more_page/faq.blade.php
<x-frontend.layout.master>
    @slot('title')
        FAQ
    @endslot
    <div class="container d-flex justify-content-center">
        @if(isset($banner->image))
        <div class="card ">
            <img src="{{ asset('/storage/banner/' . $banner->image) }}" alt="Banner"style="width:100%">
        </div>
        @endif
    </div>

    <section class="gray-bg mt-5">

        <div class="mx-auto text-center">
            <h3><span>Frequently </span> Asked Questions</h3>
            <p>Appland is completely creative, lightweight, clean &amp; super responsive app landing page.</p>
        </div>

        <div class="card w-75 mx-auto mb-5">
            <div class="accordion accordion-flush" id="accordionFlushExample">
                @foreach ($faqs as $faq)
                    @if (@isset($faq->answer))
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="flush-headingOne">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#flush-collapseOne{{ $faq->id }}" aria-expanded="false"
                                    aria-controls="flush-collapseOne">
                                    {{ $faq->comment }}
                                </button>
                            </h2>
                            <div id="flush-collapseOne{{ $faq->id }}" class="accordion-collapse collapse"
                                aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                                <div class="accordion-body">{{ $faq->answer }}</div>
                            </div>
                        </div>
                    @endif
                @endforeach
            </div>
        </div>
        <div class="card w-75 mx-auto mb-5">
            <x-frontend.form.card_header text="Do You Have Any Questions" class="text-white" />
            <div class="card-body">
                <form class="row g-3" method="POST" action="{{ route('faqs.store') }}">
                    @csrf
                    <x-backend.alertmessage.alertmessage type="success" />
                    <div class="col-md-6">
                        <x-frontend.forms.input name="name" type="text" id="name" :value="old('name')" />
                    </div>
                    <div class="col-md-6">
                        <x-frontend.forms.input name="email" type="email" id="email" :value="old('email')" />
                    </div>
                    <br>
                    <div class="col-12">
                        <x-frontend.forms.textarea name="comment" type="text" id="comment" :value="old('comment')" />
                    </div>

            </div>

            <div class="mx-auto mb-2">
                <button type="submit" class="btn btn-primary ">Send Message</button>
            </div>
            </form>
        </div>

        </div>

</x-frontend.layout.master>

</section>

resources/views/frontend/more_page/upcomingEvent.blade.php
 <x-frontend.layout.master>
    @slot('title')
    Events
    @endslot
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />


    <div class="container d-flex justify-content-center">
        @if(isset($banner->image))
        <div class="card ">
            <img src="{{ asset('/storage/banner/' . $banner->image) }}" alt="Banner"style="width:100%">
        </div>
        @endif
    </div>

<div class="container">
    <!-- start event block -->
    @foreach ($events as $event)
    <div class="row align-items-center event-block no-gutters margin-40px-bottom">
        <div class="col-lg-5 col-sm-12">
            <div class="position-relative">
                <img src="{{asset('/storage/events/'.$event->image)}}" alt="" style="width:450px;height:250px">

            </div>
        </div>
        <div class="col-lg-7 col-sm-12">
            <div class="padding-60px-lr md-padding-50px-lr sm-padding-30px-all xs-padding-25px-all">
                <h5 class="margin-15px-bottom md-margin-10px-bottom font-size22 md-font-size20 xs-font-size18 font-weight-500"><a href="event-details.html" class="text-theme-color">{{$event->title}}</a></h5>
                <ul class="event-time margin-10px-bottom md-margin-5px-bottom">
                    <li><i class="fas fa-calendar-days margin-5px-right"></i> Date : {{$event->date}}</li>
                      <li><i class="far fa-clock margin-10px-right"></i> {{$event->time}}</li>
                    <li><i class="fas fa-user margin-5px-right"></i> Speaker : {{$event->cheif_guest}}</li>
                    <li><i class="fas fa-location-dot margin-5px-right"></i> Location : {{$event->venue}}</li>


                </ul>

            <p>
              {{ substr(strip_tags($event->details), 0, 150) }}
            @if (strlen(strip_tags($event->details)) > 150)
               <a href="{{route('eventDetails', ['id' => $event->id])}}" class=" btn btn-outline-dark btn-sm">Read More</a>
            @endif

            </p>

                <!--<p>$event->details</p>
                <a class="butn small margin-10px-top md-no-margin-top" href="event-details.html">Read More <i class="fas fa-long-arrow-alt-right margin-10px-left"></i></a>-->
            </div>
        </div>
    </div>
    <hr>
    @endforeach
    <!-- end event block -->



</div>

</x-frontend.layout.master>